---
  
#**************************************************************
# Playbook :  Fait une copie de la bdd et de l'instance web 
#             copie la bdd dans mnt/mysql_backup
#             copie l'instance dans /mnt/web_backup
#**************************************************************

- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  # une tâche principale
  tasks:  

    # Créer le dossier de sauvegarde "web_backup" de l'instance de wordpress dans /mnt/
    # avec les propriétés, group et droits adequates
    - name: créé le dossier de sauvegarde de l'instance de wordpress
      file:
        path: /mnt/web_backup
        owner: root
        group: mysql
        mode: '0774'
        state: directory
      tags:
        - mysql

    # Copie et compresse l'instance web puis la déplace 
    # dans le dossier /var/www/"'nomdu hosts'.tgz"
    - name: copie et compresse l'instance web puis la déplace 
      community.general.archive:
        path: /var/www/{{ item }}
        dest: /mnt/web_backup/{{ item }}.tgz
      loop: "{{ http_host }}"

    # Créer le dossier de sauvegarde "mysql_backup de la bdd dans /mnt/
    # avec la propriété root, le group mysql et les droits adequates
    - name: créé le dossier de sauvegarde de la bdd
      file:
        path: /mnt/mysql_backup
        owner: root
        group: mysql
        mode: '0774'
        state: directory
      tags:
        - mysql

    # Créer une sauvegarde de la bdd et la déplace 
    # dans le dossier /var/www/backup/"'nomdu hosts'-'date'-'heure'.sql"
    # La variable du mot de passe root se trouve dans defaults.yml
    - name: créé une sauvegarde la bdd et la déplace
      mysql_db:
        state: dump
        name: all
        target: '/mnt/mysql_backup/{{ item }}-{{ ansible_date_time.date }}-{{ ansible_date_time.time }}.sql'
        login_user: root
        login_password: "{{ mysql_root_password }}"
      loop: "{{ http_host }}"
      tags: [ mysql ]


