---

#********************************************************************
# Playbook : fait une copie de la bdd  et de l'instance de wordpress
#********************************************************************

#MySQL 
mysql_root_password: "motDePassRoot"
mysql_db: "dbwordpress"
mysql_user: "dbadmin"
mysql_password: "dbxpass"

# Synchroniser avec l'inventaire hosts
# L'installation doit s'effectuer par machine sinon les automatisations seront en doublon !!!!
http_host: [ 'p6-u18-web']
http_port: "80"

